package com.github.leaderelection;

import java.io.Serializable;
import java.util.function.Function;

/**
 * A skeleton id provider. Note that id's generated by this provider are expected to be immutable.
 * 
 * @author gaurav
 */
public interface Id extends Serializable, Function<Void, String>, Comparable<Id> {

  @Override
  default String apply(Void blah) {
    return getId();
  }

  String getId();
}
